### ISSUE TITLE
SteamDeck update compatibility

### ISSUE THREAD

**Issue by isonil** [ubergarm/RimWorld-KanbanStockpile#20]
Hello,

We've received a report here at Ludeon that there are issues with this mod on the unstable Beta branch on Steam with the SteamDeck update. It'd be great if you could take a look.

You could use loadFolders like so:

```
<loadFolders>
   <v1.3.3311>
     <!-- after the update -->
   </v1.3.3311>
   <v1.3>
     <!-- before the update -->
   </v1.3>
</loadFolders>
```

Thanks.

[More info](https://docs.google.com/document/d/e/2PACX-1vSOOrF961tiBuNBIr8YpUvCWYScU-Wer3h3zaoMrw_jc8CCjMjlMzNCAfZZHTI2ibJ7iUZ9_CK45IhP/pub)

**Comment by ubergarm** [comment]
Thanks for the report and info, I'm getting folks reporting the issue on steam workshop as well.

Apparently the GUI is no longer rendering, so probably something changed given I was using a transpiler patch:
https://github.com/ubergarm/RimWorld-KanbanStockpile/blob/master/Source/Patches.cs#L35

## Plan
- use `<loadFolders>` to split out versions for before/after update
- figure out new transpiler patch to drawGUI again in updated version
- push fixes to steam workshop
