### ISSUE TITLE
Stack Size Limit

### ISSUE THREAD

**Issue by laughingowl** [ubergarm/RimWorld-KanbanStockpile#21]
In addition to # similar item stacks,

Would an option to limit the stack size be possible.

While there are some like this (that limit # of stacks) and some that limit stack size,  only mod I can find that is supposed to limit both is Variety Matters: Stockpile  and atleast with LWM DS and PUAH,  it seems to bug out,  and very often ignore buth #stacks and stack size limits.

**Comment by ubergarm** [comment]
Thanks @laughingowl i finally realized who you are and added you on Steam! :) Doing some mod cleanup this weekend for 1.4 and am currently taking a peek at this.

I see that someone already tried adding it in a fork here: https://github.com/Tmq5521/RimWorld-KanbanStockpile

If I can get that to merge with my latest 1.4 branch, I may do an un-official release of the mod for you to try out. I don't know if that patch is multiplayer compatible or not, and TBH I am not sure the status of MultiPlayer Mod for 1.4 yet.

#### References
* [Steam Workshop KanbanStockpile Discussion](https://steamcommunity.com/workshop/filedetails/discussion/2287142613/3101264555068062663/)

**Comment by ubergarm** [comment]
@laughingowl - I managed to merge the code from Tmq5521 and it seems to work in my limited testing!  Let me know if this suits your needs - especially with all the changes in 1.4.

I do this for fun, but if you wanted to support feel free to check out my "pay what you want" eBook of mystical poetry over at [emptyduck.com](emptyduck.com) xD

Cheers and thanks for your patience and good documentation of feature request!

**Comment by ubergarm** [comment]
Thanks @Tmq5521 for your contribution! I've released KanbanStockpile mod version v1.1.1 with your implementation and updated for Rimworld v1.4.

I added your name and give you full credit for this feature! Thanks and cheers!
