### ISSUE TITLE
?What's with PUAH and LWM?

### ISSUE THREAD

**Issue by leoric** [ubergarm/RimWorld-KanbanStockpile#25]
there is a fork https://github.com/bananasss00/RimWorld-KanbanStockpile with a bunch of commits regarding those mods.
Granted, the code there isn't clean, but maybe it's worth looking into?

Also, why no compiled releases?

**Comment by ubergarm** [comment]
PUAH = Pickup And Haul
LWM = LittleWhiteMouse - a mod dev who made a Deep Storage mod

Yes, this fork already has some code from `bananasss00` - I couldn't `git cherry-pick` their work so it doesn't actually show their name in this branch. That fork seems related to a specific modpack and rimworld version.

Regarding the compiled releases, I don't check binary blobs into github. If you want the compiled releases they are available from steam workshop for the latest version.

Hope that helps! If you have any specific feature request or issue feel free to open another ticket, cheers!
