### ISSUE TITLE
Settings are broken when a shelf is renamed

### ISSUE THREAD

**Issue by llunak** [ubergarm/RimWorld-KanbanStockpile#29]
Shelves no longer properly update their settings such as 'Similar stacks'.

Steps to reproduce:
- Start a new game (dev quickstart).
- Place two shelves.
- Set 'Stack Size' and 'Similar Stacks' for one of them.
- Click between them to see that the settings shown are different depending on which shelf is active.
- Rename both shelves.
- Observe that the settings are lost.
- Moreover the settings are now shared. If they are changed for one shelf, they change also for the other one.

**Comment by ubergarm** [comment]
Interesting, thanks for reporting. The settings are stored internally based on the name of the storage. In previous versions the rename would trigger an update. That trigger function patch probably not firing in newer versions.

Sorry for the inconvenience!

**Comment by ubergarm** [comment]
This is repeat of #27 so going to close this one and track it there. Thanks for the confirmation!
