### ISSUE TITLE
Kanban settings are applied to every storage on the map

### ISSUE THREAD

**Issue by samche2000** [ubergarm/RimWorld-KanbanStockpile#30]
Hello

Looks like something weird happens with DWM deep storage, when kanban settings are applied to a storage with linked settings, they'll copy to every storage on the map.

Linked or unlinked storages are concerned.

Thank you for your help

**Comment by ubergarm** [comment]
Thanks, as the mod was made way back in 1.2 it does not yet support linked storage. Sorry for the inconvenience.

Going to close this one as it is repeat of #28 

Thanks
